name = "GenomicBreedingPlots"
uuid = "2d71191b-ccd5-4418-88d2-30d4b74b1774"
authors = ["jeffersonparil@gmail.com"]
version = "0.1"

[deps]
CairoMakie = "13f3f980-e62b-5c42-98c6-ff1f3baf88f0"
Clustering = "aaaa29a8-35af-508c-8bc3-b662a17a0fe5"
ColorSchemes = "35d6a980-a343-548e-a6ea-1d62b119f2f4"
DataFrames = "a93c6f00-e57d-5684-b7b6-d8193f3e46c0"
Distances = "b4f34e82-e78d-54a5-968a-f98e89d6e8f7"
Distributions = "31c24e10-a181-5473-b8eb-7969acd0382f"
Documenter = "e30172f5-a6a5-5a46-863b-614d45cd2de4"
GenomicBreedingCore = "50d95318-1838-4cfa-a614-3543b4bb0509"
LinearAlgebra = "37e2e46d-f89d-539d-b4ee-838fcccc9c8e"
Measures = "442fdcdd-2543-5da2-b0f3-8c86c306513e"
MultivariateStats = "6f286f6a-111f-5878-ab1e-185364afe411"
Random = "9a3f8284-a2c9-5f02-9a11-845980a1fd5c"
StatsBase = "2913bbd2-ae8a-5f71-8c99-4fb6c76f3a91"

[sources]
GenomicBreedingCore = {rev = "main", url = "https://github.com/GenomicBreeding/GenomicBreedingCore.jl"}

[compat]
CairoMakie = "0.13.1"
Clustering = "0.15.8"
ColorSchemes = "3.27.1"
DataFrames = "1.7.0"
Distances = "0.10.12"
Distributions = "0.25.116"
Documenter = "1.8.0"
GenomicBreedingCore = "1.0.0"
LinearAlgebra = "1.11.0"
Measures = "0.3.2"
MultivariateStats = "0.10.3"
Random = "1.11.0"
StatsBase = "0.34.4"
julia = "1.11"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
